const TEAMS={"North Team": ["Senan Alkawamleh", "Carlo Mendez", "Ummer Mohd", "Mohamed Alanazi", "Jamjom", "Faizal", "Momen Hasan"], "Central Team": ["Muhanned Hassan", "Sheikoli Mydeen", "Mogtaba Ahmad", "Muaaz Hezam", "Ahmed Nasser", "Khalid Erhaim"], "East Team": ["Moataz Tammam", "Nayyar Abbas", "Marwan Elgurshi", "Elmer Salcedo", "Hassan Alkhabbaz", "Musa Elsiddig", "Nhec Inao"], "South Team": ["Abdullah Gomaa", "El-Sayed Eissa", "Mohammed Arif", "Abdulrahim Bawazeer", "Hussain Al Zeidan", "Amri Alkhidder", "Arsalan khan"], "Al-Kharj Team": ["Devid Gromio", "Ibrahim Qaysi"], "Hail Team": ["Ieyad Khany", "Ahmed Tawhal"], "Qassim Team": ["Mamdouh Saibi", "Manzul Kasim", "Rehmatullah", "Joel Malicdem", "Yousif Yassen", "Tariq Elobaid"], "Dawadmi Team": ["Sherif Wagdi"]};
const A={name:["ce name","employee name","employee","engineer name","engineer","name"],code:["ce code","employee code","emp code","engineer code","code"],date:["date","activity date","call date","week start","month"],slm:["7 day slm revisit","7 day revisit","slm revisit","slm"],ccpdw:["ccpdw"],retrip:["re-trip","retrip","re trip"],sla:["sla response","response sla","sla"],util:["utilization","utilisation"],fund:["call fundamentals","fundamentals"],closed:["closed srs","closed sr","closed service requests","closed"],opp:["response opp","response opportunity","response opportunities"]};
const state={records:JSON.parse(localStorage.getItem("CE_PERF_DB")||"[]"),page:"dashboard",team:"ALL",period:"ALL",q:""};
const $=x=>document.getElementById(x);
const norm=x=>String(x??"").toUpperCase().trim().replace(/[^A-Z0-9]+/g," ").replace(/\s+/g," ").trim();
const comp=x=>norm(x).replace(/\s/g,"");
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function col(h,aa){let n=h.map(norm);for(let a of aa){let i=n.indexOf(norm(a));if(i>=0)return i}for(let a of aa){let i=n.findIndex(x=>x.includes(norm(a)));if(i>=0)return i}return -1}
function num(v){if(v===""||v==null)return null;let s=String(v).replace(/,/g,""),p=s.includes("%");s=s.replace("%","");let n=parseFloat(s);return Number.isFinite(n)?p?n/100:n:null}
function cname(v){let n=norm(v);for(let m of Object.values(TEAMS)){let e=m.find(x=>norm(x)==n);if(e)return e}let a={"NHEC NJ INAO":"Nhec Inao","NHEC NJ A INAO":"Nhec Inao","MARWAN ELGORSCH":"Marwan Elgurshi","MARWAN ELGORSH":"Marwan Elgurshi"};return a[n]||String(v||"").trim()}
function getTeam(n){n=cname(n);for(let [t,m] of Object.entries(TEAMS))if(m.some(x=>norm(x)==norm(n)))return t;return"Unassigned"}
function dt(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000);let d=new Date(v);return isNaN(d)?null:d}
function week(d){if(!d)return"Current Snapshot";let y=new Date(d.getFullYear(),0,1),n=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-y)/86400000);return d.getFullYear()+"-W"+String(Math.floor((n+y.getDay())/7)+1).padStart(2,"0")}
function month(d){return d?d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0"):"Current Snapshot"}
function parse(rows,h,file){let i={};for(let k in A)i[k]=col(h,A[k]);if(i.name<0&&i.code<0)throw Error("Excel must contain CE Name or CE Code.");return rows.flatMap((r,z)=>{let raw=i.name>=0?r[i.name]:"",code=i.code>=0?r[i.code]:"";if(String(raw).trim()===""&&String(code).trim()==="")return[];let n=cname(raw||code),d=i.date>=0?dt(r[i.date]):null;return[{id:Date.now()+"-"+z+"-"+Math.random(),name:n,code:String(code||"").trim(),team:getTeam(n),week:week(d),month:month(d),slm:i.slm>=0?num(r[i.slm]):null,ccpdw:i.ccpdw>=0?num(r[i.ccpdw]):null,retrip:i.retrip>=0?num(r[i.retrip]):null,sla:i.sla>=0?num(r[i.sla]):null,util:i.util>=0?num(r[i.util]):null,fund:i.fund>=0?num(r[i.fund]):null,closed:i.closed>=0?num(r[i.closed]):null,opp:i.opp>=0?num(r[i.opp]):null}]})}
function score(v,t,dir){if(v==null)return null;if(t===0)return dir==="low"?(v<=0?100:Math.max(0,100-v*100)):100;if(dir==="high")return Math.min(100,v/t*100);return v<=t?100:Math.max(0,t/v*100)}
function pct(rows,k,dir){let a=rows.filter(x=>x[k]!=null),v=a.map(x=>+x[k]),m=new Map();a.forEach(x=>{let b=dir==="high"?v.filter(z=>z>x[k]).length:v.filter(z=>z<x[k]).length;m.set(x.id,100*(v.length-b-1)/Math.max(1,v.length-1))});return m}
function calc(rows){let c=pct(rows,"closed","high"),o=pct(rows,"opp","low");return rows.map(x=>{let s=[];let m={};for(let k of ["slm","ccpdw","retrip","sla","util","fund"]){let t={slm:0,ccpdw:4,retrip:0,sla:1,util:1,fund:1}[k],d=["ccpdw","sla","util","fund"].includes(k)?"high":"low";m[k]=score(x[k],t,d);if(m[k]!=null)s.push(m[k])}m.closed=c.get(x.id)??null;m.opp=o.get(x.id)??null;if(m.closed!=null)s.push(m.closed);if(m.opp!=null)s.push(m.opp);return{...x,score:s.length?s.reduce((a,b)=>a+b,0)/s.length:null}})}
function filtered(){let r=state.records;if(state.team!="ALL")r=r.filter(x=>x.team==state.team);if(state.period!="ALL")r=r.filter(x=>x.week==state.period||x.month==state.period);let q=norm(state.q),cq=comp(state.q);if(q)r=r.filter(x=>norm(x.name).includes(q)||norm(x.code).includes(q)||comp(x.name).includes(cq)||comp(x.code).includes(cq));return r}
function ranked(r){return calc(r).sort((a,b)=>(b.score??-1)-(a.score??-1)).map((x,i)=>({...x,rank:i+1}))}
function pv(v){return v==null?"—":(v*100).toFixed(1)+"%"}function nv(v){return v==null?"—":Number(v).toLocaleString()}
function badge(s){return s==null?'<span class="badge none">No Score</span>':s>=85?'<span class="badge good">Outstanding</span>':s>=70?'<span class="badge good">Strong</span>':s>=55?'<span class="badge mid">Developing</span>':'<span class="badge bad">Needs Improvement</span>'}
function table(rows){let r=ranked(rows);if(!r.length)return'<div class="empty">No records found.</div>';return'<div class="wrap"><table><thead><tr><th>Rank</th><th>CE Name</th><th>CE Code</th><th>Team</th><th>Score</th><th>Status</th><th>7 Day SLM</th><th>CCPDW</th><th>Re-trip</th><th>SLA</th><th>Util.</th><th>Fund.</th><th>Closed SRs</th><th>Response Opp</th></tr></thead><tbody>'+r.map(x=>`<tr><td><b>#${x.rank}</b></td><td><b>${esc(x.name)}</b></td><td>${esc(x.code)}</td><td>${esc(x.team)}</td><td><b>${x.score==null?"—":x.score.toFixed(1)}</b></td><td>${badge(x.score)}</td><td>${pv(x.slm)}</td><td>${nv(x.ccpdw)}</td><td>${pv(x.retrip)}</td><td>${pv(x.sla)}</td><td>${pv(x.util)}</td><td>${pv(x.fund)}</td><td>${nv(x.closed)}</td><td>${nv(x.opp)}</td></tr>`).join("")+"</tbody></table></div>"}
function setFilters(){team.innerHTML='<option value="ALL">All Teams</option>'+Object.keys(TEAMS).map(t=>`<option>${esc(t)}</option>`).join("");team.value=state.team;let p=[...new Set(state.records.flatMap(x=>[x.week,x.month]))].filter(Boolean).sort().reverse();period.innerHTML='<option value="ALL">All Periods</option>'+p.map(x=>`<option>${esc(x)}</option>`).join("");period.value=state.period;search.value=state.q}
function dashboard(){let r=ranked(filtered()),s=r.map(x=>x.score).filter(x=>x!=null),a=s.length?s.reduce((p,q)=>p+q,0)/s.length:null;app.innerHTML=`<div class="cards"><div class="card">Records<b>${r.length}</b></div><div class="card">Average Score<b>${a==null?"—":a.toFixed(1)}</b></div><div class="card">Top Performer<b>${esc(r[0]?.name||"—")}</b></div><div class="card">Teams<b>8</b></div><div class="card">Employees<b>38</b></div></div><div class="panel"><h2>Top Ranking</h2>${table(r.slice(0,10))}</div>`}
function teamsPage(){app.innerHTML='<div class="teams">'+Object.entries(TEAMS).map(([t,m])=>`<div class="team"><h3>${esc(t)} (${m.length})</h3><ul>${m.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`).join("")+"</div>"}
function rulesPage(){app.innerHTML='<div class="panel"><h2>Performance Rules</h2><table><tr><th>Metric</th><th>Target</th><th>Direction</th></tr><tr><td>7 Day SLM Revisit</td><td>0%</td><td>Lower is better</td></tr><tr><td>CCPDW</td><td>4</td><td>Higher is better</td></tr><tr><td>Re-trip</td><td>0%</td><td>Lower is better</td></tr><tr><td>SLA Response</td><td>100%</td><td>Higher is better</td></tr><tr><td>Utilization</td><td>100%</td><td>Higher is better</td></tr><tr><td>Call Fundamentals</td><td>100%</td><td>Higher is better</td></tr><tr><td>Closed SRs</td><td>Percentile</td><td>Higher is better</td></tr><tr><td>Response Opp</td><td>Percentile</td><td>Lower is better</td></tr></table></div>'}
function employeesPage(){let ns=[...new Set(filtered().map(x=>x.name))].sort();app.innerHTML='<div class="panel"><h2>Employees</h2><div class="wrap"><table><tr><th>Name</th><th>Code</th><th>Team</th><th>Records</th></tr>'+ns.map(n=>{let x=filtered().filter(z=>z.name==n)[0];return`<tr><td>${esc(n)}</td><td>${esc(x.code)}</td><td>${esc(x.team)}</td><td>${filtered().filter(z=>z.name==n).length}</td></tr>`}).join("")+'</table></div></div>'}
function render(){setFilters();let titles={dashboard:["Dashboard","Customer Engineer performance monitoring"],ranking:["Ranking","Employee ranking"],weekly:["Weekly Performance","Weekly results"],monthly:["Monthly Performance","Monthly results"],employees:["Employees","Employee database"],teams:["Teams","Team database"],rules:["Performance Rules","Configured performance targets"]};title.textContent=titles[state.page][0];sub.textContent=titles[state.page][1];document.querySelectorAll("aside button").forEach(b=>b.classList.toggle("active",b.dataset.p==state.page));if(state.page=="dashboard")dashboard();else if(state.page=="ranking")app.innerHTML='<div class="panel"><h2>Current Ranking</h2>'+table(filtered())+'</div>';else if(state.page=="weekly")periodPage("week");else if(state.page=="monthly")periodPage("month");else if(state.page=="employees")employeesPage();else if(state.page=="teams")teamsPage();else rulesPage()}
function periodPage(k){let r=filtered(),g=[...new Set(r.map(x=>x[k]))].sort().reverse();app.innerHTML=g.map(p=>`<div class="panel"><h2>${esc(p)}</h2>${table(r.filter(x=>x[k]==p))}</div>`).join("")||'<div class="empty">No data.</div>'}
document.querySelectorAll("aside button").forEach(b=>b.onclick=()=>{state.page=b.dataset.p;render()});
team.onchange=()=>{state.team=team.value;render()};period.onchange=()=>{state.period=period.value;render()};search.oninput=()=>{state.q=search.value;render()};clear.onclick=()=>{state.team="ALL";state.period="ALL";state.q="";render()};
upload.onclick=()=>modal.classList.add("show");close.onclick=()=>modal.classList.remove("show");
file.onchange=async()=>{let f=file.files[0];if(!f)return;try{let wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true}),sh=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sh,{header:1,defval:"",raw:true});state.records.push(...parse(rows.slice(1),rows[0],f.name));localStorage.setItem("CE_PERF_DB",JSON.stringify(state.records));modal.classList.remove("show");render();alert("Excel imported successfully.")}catch(e){alert("Import error: "+e.message)}};
render();
