*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:#f4f7fb;color:#172033}
.app{display:flex;min-height:100vh}aside{width:235px;background:#102a43;color:white;position:fixed;inset:0 auto 0 0;padding:20px 14px}
.brand{display:flex;align-items:center;gap:10px;padding:5px 8px 25px}.brand b{background:#2f80ed;border-radius:9px;padding:11px}.brand span{font-weight:700}
nav{display:grid;gap:7px}.nav{border:0;background:transparent;color:#d9e4ef;text-align:left;padding:12px;border-radius:8px;cursor:pointer}.nav.active,.nav:hover{background:#21496d;color:#fff}
main{margin-left:235px;width:calc(100% - 235px);padding:25px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}h1{margin:0;font-size:25px}header p{color:#718096;margin:5px 0}
.primary,.secondary{border:0;border-radius:8px;padding:10px 15px;cursor:pointer;font-weight:700}.primary{background:#2f80ed;color:#fff}.secondary{background:#e8eef5;color:#243b53}
.filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap;background:white;border:1px solid #e1e8f0;border-radius:12px;padding:13px;margin-bottom:20px}.filters label{font-size:11px;font-weight:700;color:#66768a;display:grid;gap:5px}.filters select,.filters input{height:38px;border:1px solid #ccd6e0;border-radius:7px;padding:0 10px;min-width:175px}.filters input{min-width:290px}.filters input:focus{outline:2px solid #c8e0ff;border-color:#2f80ed}
.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-bottom:20px}.card,.panel,.teamcard{background:white;border:1px solid #e1e8f0;border-radius:12px;padding:17px}.card .label{font-size:10px;color:#758397;font-weight:700;text-transform:uppercase}.card .value{font-size:23px;font-weight:800;margin-top:7px}.card .sub{font-size:11px;color:#8291a4;margin-top:5px}
.panel{margin-bottom:18px}.panel h2{font-size:16px;margin:0 0 14px}.grid2{display:grid;grid-template-columns:1.5fr 1fr;gap:18px}
.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}th{background:#eef4f9;color:#40536a;text-align:left;padding:9px;white-space:nowrap}td{padding:9px;border-bottom:1px solid #edf1f5;white-space:nowrap}tr:hover td{background:#f8fbfd}.rank{font-weight:800}
.badge{padding:4px 8px;border-radius:20px;font-size:10px;font-weight:800}.out{background:#dff3e5;color:#23753d}.strong{background:#e0efff;color:#23629a}.dev{background:#fff0d7;color:#946200}.need{background:#fde2e2;color:#a33a3a}.none{background:#e9edf2;color:#536579}
.metricgrid,.teamgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric{border:1px solid #e5ebf1;border-radius:9px;padding:12px}.metric b{font-size:11px;color:#6c7b8d}.metric strong{display:block;margin-top:6px}.teamgrid{grid-template-columns:repeat(3,1fr)}.teamcard h3{margin:0 0 8px}.teamcard ul{font-size:12px;line-height:1.8;margin:0;padding-left:18px}
.empty{text-align:center;padding:55px;color:#748398}.drop{border:2px dashed #a9bbce;border-radius:12px;padding:45px;text-align:center;color:#58708a;cursor:pointer}.drop small{display:block;margin-top:8px}
.modal{display:none;position:fixed;inset:0;background:#0008;align-items:center;justify-content:center}.modal.show{display:flex}.modalbox{position:relative;background:white;border-radius:14px;padding:25px;width:min(560px,92vw)}.x{position:absolute;right:12px;top:8px;border:0;background:none;font-size:25px}
.notice{padding:12px;background:#fff4db;border-radius:8px;font-size:12px;color:#795b13}.small{font-size:11px;color:#718096}
@media(max-width:1000px){.cards{grid-template-columns:repeat(3,1fr)}.grid2{grid-template-columns:1fr}.metricgrid,.teamgrid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:700px){aside{position:static;width:100%;height:auto}.app{display:block}main{margin:0;width:100%;padding:15px}.cards,.metricgrid,.teamgrid{grid-template-columns:1fr}}
